### ISSUE TITLE
Missing Common Words

### ISSUE THREAD

**Issue by tbrknt** [MeteHanC/turkishnlp#1]
I know it is a very early version; however, there are some common words that are not contained in the word list of the package. Thus, they are 'corrected' with the auto_correct function. 

Some missing common words are the following, most of which are obtained from [Wiktionary's List of 1000 Most Frequent Words of Turkish](https://en.wiktionary.org/wiki/Wiktionary:Frequency_lists/Turkish ):

> ve, bu, o, ben, ne, yer, en, her, el, ev, gerekmek, durum, bile, son, hem, adam, ses, para, anne, an, ad, ay, alan, Allah, program, film, on, ana, can, internet, kent, mal, sol, model, yetmek, tip, beri, dost, din, plan, et, salon, metre, top, normal, boy, roman, hata, problem, gene, Tanrı, risk, organ, modern, at, site, vitamin, git

Can you update word list if possible?

**Comment by MeteHanC** [comment]
Hello,

Yes,  actually this is a known issue. I am thinking about re-creating the word list from scratch. But yes, adding the common words could be useful in short-term. I will add them when I can and let you know.

**Comment by MeteHanC** [comment]
I have updated the wordset. Should be fixed now with #[8518141](https://github.com/MeteHanC/turkishnlp/commit/851814185772b813fe6dd8c18e3cbb67a012246c) . You can re-call the download function and it will overwrite the file. And there also typos in some words, I will create a clean dataset asap. Please confirm that it is fixed, so I can close the issue

**Comment by tbrknt** [comment]
I have tested it and it works. 

Thanks for that quick fix.
