### ISSUE TITLE
Download link doesnt work

### ISSUE THREAD

**Issue by snickersxs** [MeteHanC/turkishnlp#2]
http://metehancetinkaya.com/datanlp/

**Comment by MeteHanC** [comment]
Hey, the website is down for good. I will replace that asap. Thanks for letting me know

**Comment by MeteHanC** [comment]
Should be fixed with #[ee6a7eb](https://github.com/MeteHanC/turkishnlp/commit/ee6a7eb41a944f843a83bd223a897b7f551d24e8)
