### ISSUE TITLE
Detector.py "kelimeler.txt" not found error.

### ISSUE THREAD

**Issue by snickersxs** [MeteHanC/turkishnlp#3]
File "/env/lib/python3.7/site-packages/turkishnlp/detector.py", line 36, in create_word_set
    with open("kelimeler.txt", "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'kelimeler.txt'

--In code ı cant find kelimeler.txt file code in line 36, but python gives thies error. Is there any problem ?What does it do ("kelimeler.txt")?

thanks

**Comment by MeteHanC** [comment]
Hello,

Creating the word list from a text file was in the initial release, and it should be deleted, yet if you downloaded the files without an error you should not be getting this error. Did you try downloading the dataset as it was instructed on the documentation page?

```
from turkishnlp import detector
obj = detector.TurkishNLP()
obj.download()
```

You should call the download function once, and you are good to go after that.

Let me know if the problem persists

Thank you
