### ISSUE TITLE
merhaba anaconda python3.7.3 de hata alıyorum yardımcı olurmusunuz

### ISSUE THREAD

**Issue by hasbeeen** [MeteHanC/turkishnlp#4]
Collecting turkishnlp
  Using cached https://files.pythonhosted.org/packages/a5/ea/d3a5b072847e05d123eed0e49dd420b8bd5415b499439499196ab2b1486f/turkishnlp-0.0.6.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\HASBI_~1\AppData\Local\Temp\pip-install-vb89_lmg\turkishnlp\setup.py", line 9, in <module>
        long_description=open('README.md').read(),
      File "D:\Anaconda3\envs\home_asistan\lib\encodings\cp1254.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9e in position 3747: character maps to <undefined>
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\HASBI_~1\AppData\Local\Temp\pip-install-vb89_lmg\turkishnlp\

**Comment by MeteHanC** [comment]
Merhaba

Hatayı tekrarlatamadığım için çalışıp çalışmadığını kontrol edemedim. Ancak sorunun muhtemel fix'i :  #[507af76](https://github.com/MeteHanC/turkishnlp/commit/507af76ece9a2223e756559b4ca218cb6992fc17) . 

Ayrıca 0.0.61 versiyonu olarak da yayınladım. 


`pip3 install turkishnlp==0.0.61` yada `conda install turkishnlp=0.0.61` kullanarak tekrar deneyebilir misiniz?
