### ISSUE TITLE
pickle guvenlik sorunu

### ISSUE THREAD

**Issue by sinancetinkaya** [MeteHanC/turkishnlp#5]
detetector.py dosyasini inceledigimde http://turkish-nlp.com sitesiden pickle dosyalari indirip yukledigini goruyorum.

kodunuzu pickle kullanmayacak sekilde yeniden yazmalisiniz.
pickle dosyalarinda su an herhangi sorun olmamasina ragmen ileride bu dosyalarin degistirilmesi ciddi guvenlik sorunu dogurur.

pickle ile guvenlik uyarisina buradan ulasabilirsiniz https://docs.python.org/3/library/pickle.html#pickle-python-object-serialization

**Comment by MeteHanC** [comment]
Merhabalar, uyarınız için teşekkürler.

Daha önceden işlenen kelimeleri, program akışının yavaş olmaması için Pickle'da tutuyorum. Bunları her fonksiyon çağrılışında tekrar işlemek performansı olumsuz yönde etkileyecektir. Redis gibi bir in-memory yazılım ile cacheleme yapılabilir ancak gereksiz yere proje karmaşıklığını arttıracağı için buna gerek duymuyorum. 

Ayrıca proje zaten açık kaynak, istenildiği taktirde gerekli liste ve dictionary'ler, farklı datasetler'den rahatlıkla oluşturulabilir.

**Comment by sinancetinkaya** [comment]
Verileri json olarak indirip host makinada pickle oluşturup saklayabilirsiniz. Burada sorun harici bir kaynaktan pickle olarak indirilmesi. Bu dosyalar ileride kötü amaçlı değiştirilebilirler.
